version: '3.8'

services:
  rl-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rl_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/project
    working_dir: /workspace
    restart: unless-stopped
    networks:
      - rl_network
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

networks:
  rl_network:
    driver: bridge
